services:
  AD-Meeting-Calendar:
    build:
      context: .
    container_name: AD-Meeting-Calendar-service
    ports:
      - "8000:8000"
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: AD-Meeting-Calendar-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
      MONGO_INITDB_DATABASE: mymcdatabase
    ports:
      - "27111:27017"
    volumes:
      - AD-Meeting-Calendar-mongodb:/data/db/mongodb

  postgresql:
    image: postgres:15
    container_name: AD-Meeting-Calendar-postgresql
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mymcdatabase
    ports:
      - "5112:5432"
    volumes:
      - AD-Meeting-Calendar-postgresql:/data/db/postgresql

volumes:
  AD-Meeting-Calendar-mongodb:
    driver: local
  AD-Meeting-Calendar-postgresql:
    driver: local
